[package]
name = "mockchain_v2" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Andrew Macmillan"]

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
